language: node_js
node_js:
  - "lts/*"
  - "14"
after_success:
  - npm install coveralls && nyc report --reporter=text-lcov | coveralls
  - openssl aes-256-cbc -K $encrypted_db2ce12ff441_key -iv $encrypted_db2ce12ff441_iv -in deploy_key.enc -out deploy_key -d
  - bash autodeploy.sh
