language: node_js
node_js:
  - "4"
  - "5"
after_success:
  - openssl aes-256-cbc -K $encrypted_d96e3d89b2d4_key -iv $encrypted_d96e3d89b2d4_iv -in deploy_key.enc -out deploy_key -d
  - bash autodeploy.sh
